### ISSUE TITLE
linux-rga 有两个分支 master  和 im2d分支  这两个分支有什么区别？ rk3288 要下载哪个分支的代码做转码？

### ISSUE THREAD

**Issue by wangjl-william** [rockchip-linux/linux-rga#16]
linux-rga 有两个分支 master  和 im2d分支  这两个分支有什么区别？ rk3288 要下载哪个分支的代码做转码？

**Comment by JeffyCN** [comment]
im2d ~= master(legacy RGA API) + new im2d API(requires matched kernel version)
