### ISSUE TITLE
rk3288 ubuntu18.04 配置完 cmake-linux.sh 以后进行编译 编译报错，请大神帮忙处理，谢谢。

### ISSUE THREAD

**Issue by wangjl-william** [rockchip-linux/linux-rga#17]
root@rk3288:/home/rk3288/test_mpp/linux-rga/build# ./cmake-linux.sh 
default to Release build for GCC builds
Generated version.h
set buildroot toolchain
-- The C compiler identification is GNU 7.5.0
-- The CXX compiler identification is GNU 7.5.0
-- Check for working C compiler: /usr/bin/arm-linux-gnueabihf-gcc
-- Check for working C compiler: /usr/bin/arm-linux-gnueabihf-gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/arm-linux-gnueabihf-g++
-- Check for working CXX compiler: /usr/bin/arm-linux-gnueabihf-g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: /home/rk3288/test_mpp/linux-rga/build
Scanning dependencies of target rga
[ 10%] Building CXX object CMakeFiles/rga.dir/core/RockchipRga.cpp.o
[ 20%] Building CXX object CMakeFiles/rga.dir/core/GrallocOps.cpp.o
[ 30%] Building CXX object CMakeFiles/rga.dir/core/NormalRga.cpp.o
[ 40%] Building CXX object CMakeFiles/rga.dir/core/NormalRgaApi.cpp.o
[ 50%] Building CXX object CMakeFiles/rga.dir/core/RgaUtils.cpp.o
/home/rk3288/test_mpp/linux-rga/core/RgaUtils.cpp: In function ‘int get_buf_from_file(void*, int, int, int, int)’:
/home/rk3288/test_mpp/linux-rga/core/RgaUtils.cpp:307:10: warning: ignoring return value of ‘size_t fread(void*, size_t, size_t, FILE*)’, declared with attribute warn_unused_result [-Wunused-result]
     fread(buf, get_buf_size_by_w_h_f(sw, sh, f), 1, file);
     ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[ 60%] Building CXX object CMakeFiles/rga.dir/im2d_api/im2d.cpp.o
[ 70%] Linking CXX shared library librga.so
[ 70%] Built target rga
Scanning dependencies of target im2d
[ 80%] Building CXX object CMakeFiles/im2d.dir/samples/im2d_api_demo/rgaImDemo.cpp.o
[ 90%] Building CXX object CMakeFiles/im2d.dir/samples/im2d_api_demo/args.cpp.o
[100%] Linking CXX executable im2d
librga.so：对‘pthread_mutexattr_destroy’未定义的引用
librga.so：对‘pthread_mutexattr_setpshared’未定义的引用
librga.so：对‘pthread_mutexattr_init’未定义的引用
collect2: error: ld returned 1 exit status
CMakeFiles/im2d.dir/build.make:121: recipe for target 'im2d' failed
make[2]: *** [im2d] Error 1
CMakeFiles/Makefile2:104: recipe for target 'CMakeFiles/im2d.dir/all' failed
make[1]: *** [CMakeFiles/im2d.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by siyl** [comment]
try this command：./cmake-linux.sh -lpthread

**Comment by wangjl-william** [comment]
> try this command：./cmake-linux.sh -lpthread

retry ./cmake-linux.sh without error.thks siyl
