### ISSUE TITLE
rk3288不能使用rga

### ISSUE THREAD

**Issue by lwdddddddd** [rockchip-linux/linux-rga#2]
你好，请问rk3288能正常使用RGA吗？设备节点怎么正常开启？我执行rgaSlt没有通过测试，以下是打印信息：
root@linaro-alip:/opt/librga_linux/bin# ./sh.sh 
Rga built version:version:+2017-09-28 10:12:42 
Rga built version:version:+2017-09-28 10:12:42 
src.fd =5 
dst.fd =6 
fd-vir-phy-hnd-format[5, (nil), (nil), (nil), 0] 
rect[0, 0, 1280, 720, 1280, 720, 0, 0] 
f-blend-size-rotation-col-log-mmu[0, 0, 0, 0, 0, 0, 1] 
fd-vir-phy-hnd-format[6, (nil), (nil), (nil), 0] 
rect[0, 0, 1280, 720, 1280, 720, 0, 0] 
f-blend-size-rotation-col-log-mmu[0, 0, 0, 0, 0, 0, 1] 
This output the user patamaters when rga call blit fail 
cost_time=0 ms
rgaFillColor error : No such file or directory,hnd=0x1
open /data/out0w1280-h720-rgba8888.bin and write ok
[  num   : srcInfo    dstInfo ] 
[X00000000:0x67002851 0x0]  
[X00000001:0x66002552 0x0]  [X00000002:0x65002950 0x0]  [X00000003:0x66002850 0x0]  [X00000004:0x67002851 0x0]  
[X00000005:0x66002550 0x0]  [X00000006:0x66002650 0x0]  [X00000007:0x66002750 0x0]  [X00000008:0x66002750 0x0]  
[X00000009:0x67002950 0x0]  [X00000010:0x67002b4f 0x0]  [X00000011:0x67002a50 0x0]  [X00000012:0x6600294f 0x0]  
[X00000013:0x6600274f 0x0]  [X00000014:0x68002952 0x0]  [X00000015:0x67002851 0x0]  [X00000016:0x68002952 0x0]  
[X00000017:0x69002a53 0x0]  [X00000018:0x69002953 0x0]  [X00000019:0x68002854 0x0]  [X00000020:0x67002754 0x0]  
[X00000021:0x68002855 0x0]  [X00000022:0x68002955 0x0]  [X00000023:0x68002a55 0x0]  [X00000024:0x68002a55 0x0]  
[X00000025:0x68002955 0x0]  [X00000026:0x6a002b57 0x0]  [X00000027:0x6a002c56 0x0]  [X00000028:0x69002c55 0x0]  
[X00000029:0x6a002d56 0x0]  [X00000030:0x6b002e57 0x0]  [X00000031:0x68002b54 0x0]  [X00000032:0x6a002d56 0x0]  
[X00000033:0x6a002d56 0x0]  [X00000034:0x69002d56 0x0]  [X00000035:0x69002e57 0x0]  [X00000036:0x68002f55 0x0]  
[X00000037:0x68002e56 0x0]  [X00000038:0x67002c55 0x0]  [X00000039:0x68002d56 0x0]  [X00000040:0x69002e57 0x0]  
[X00000041:0x6a003057 0x0]  [X00000042:0x69002f56 0x0]  [X00000043:0x69002f57 0x0]  [X00000044:0x68002d56 0x0]  
[X00000045:0x69002e57 0x0]  [X00000046:0x69002e57 0x0]  [X00000047:0x69002e57 0x0]  [X00000048:0x6a003058 0x0]  
[X00000049:0x6a002f58 0x0]  [X00000050:0x6a002f58 0x0]  [X00000051:0x69002e57 0x0]  [X00000052:0x6b002f58 0x0]  
[X00000053:0x68002d56 0x0]  [X00000054:0x69002e57 0x0]  [X00000055:0x6a002e59 0x0]  [X00000056:0x69002e58 0x0]  
[X00000057:0x6a002f58 0x0]  [X00000058:0x6d00325b 0x0]  [X00000059:0x69002e57 0x0]  [X00000060:0x6c00315a 0x0]  
[X00000061:0x6b002f5a 0x0]  [X00000062:0x6b002f5a 0x0]  [X00000063:0x6b002f5a 0x0]  [X00000064:0x6a00305a 0x0]  
errCount=65,rightCount=0
rga slt err !! 
threadloop

**Comment by JeffyCN** [comment]
"No such file or directory" likely means no /dev/rga.
