### ISSUE TITLE
COPYING MD5 checksum will need updated

### ISSUE THREAD

**Issue by karltsou** [rockchip-linux/linux-rga#20]
Hi 

I was facing yocto build error that relatived to MD5 checksum number incorrect. And what are the best way to fix it, update COPYING by Rockchip or modify old MD5 number on my side? 

 rockchip-librga: Update license

License changed from GPL-2+ to Apache-2.0.

Change-Id: I3cf0e09656c101c421414f72fbf76937d918728a
Signed-off-by: Jeffy Chen <jeffy.chen@rock-chips.com>

**Comment by JeffyCN** [comment]
well, the rga's license been updated...

due to some business issue, this github might not be updated. if you are using yocto, it should use my mirrors, try to check the source uri:
SRC_URI = " \
  git://github.com/JeffyCN/mirrors.git;branch=linux-rga; \
