### ISSUE TITLE
rk3288使用ffplay播放视频画面偏蓝

### ISSUE THREAD

**Issue by amazingfate** [rockchip-linux/linux-rga#6]
系统：debian stretch
```
$ uname -a
Linux linaro-alip 4.4.154 #112 SMP Tue Jul 28 14:46:28 CST 2020 armv7l GNU/Linux
$ffmpeg -version
Rga built version:version:+2017-09-28 10:12:42
ffmpeg version 4.1.4-1 Copyright (c) 2000-2019 the FFmpeg developers
built with gcc 6.3.0 (Debian 6.3.0-18+deb9u1) 20170516
configuration: --prefix=/usr --extra-version=1 --toolchain=hardened --libdir=/usr/lib/arm-linux-gnueabihf --incdir=/usr/include/arm-linux-gnueabihf --arch=arm --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --disable-libaom --disable-libmysofa --disable-libvidstab --enable-libdrm --enable-librga --enable-rkmpp --enable-version3 --disable-libopenh264 --disable-vaapi --disable-vdpau --disable-decoder=h264_v4l2m2m --disable-decoder=vp8_v4l2m2m --disable-decoder=mpeg2_v4l2m2m --disable-decoder=mpeg4_v4l2m2m --disable-muxer='ac3,eac3,mlp,truehd' --disable-encoder='ac3_fixed,ac3,mlp,truehd' --disable-demuxer='ac3,eac3,mlp,truehd,dts,dtshd' --disable-parser='ac3,mlp' --disable-decoder='ac3,eac3,mlp,dolby_e' --enable-shared --disable-doc
libavutil      56. 22.100 / 56. 22.100
libavcodec     58. 35.100 / 58. 35.100
libavformat    58. 20.100 / 58. 20.100
libavdevice    58.  5.100 / 58.  5.100
libavfilter     7. 40.101 /  7. 40.101
libavresample   4.  0.  0 /  4.  0.  0
libswscale      5.  3.100 /  5.  3.100
libswresample   3.  3.100 /  3.  3.100
libpostproc    55.  3.100 / 55.  3.100
```
因为普通用户执行rga测试demo会报错`rgaFillColor error : Permission denied`，使用sudo可以正常使用
使用命令`sudo ffplay ~/test.mp4`播放视频，画面显示偏蓝，与正常画面偏差较大

**Comment by amazingfate** [comment]
ffmpeg调用librga的代码在 https://github.com/JeffyCN/FFmpeg/blame/master/libavcodec/rkmppdec.c
因上述仓库没有开issue，所以在这里提了@JeffyCN

**Comment by JeffyCN** [comment]
1/ permission denied, rga's device node is at /dev/rga, you can try to modify the permission. if you're using rockchip's debian SDK, there should be a /etc/udev/rules.d/60-rga.rules for it.

2/ color issue, there is a bug in the rga2 hardware, which was "fixed" in the kernel driver by:
commit b791aba486285310aa9c2ced04df5ecd080a4548
Author: Li Huang <putin.li@rock-chips.com>
Date:   Thu Nov 14 09:17:13 2019 +0800

    video/rockchip: rga2: Fixup wrong swap uv on YCrCb_420_P

    Change-Id: I907c8687c5736fb489a21d16e87addf1f67e07c1
    Signed-off-by: Li Huang <putin.li@rock-chips.com>

**Comment by amazingfate** [comment]
> 1/ permission denied, rga's device node is at /dev/rga, you can try to modify the permission. if you're using rockchip's debian SDK, there should be a /etc/udev/rules.d/60-rga.rules for it.
> 
> 2/ color issue, there is a bug in the rga2 hardware, which was "fixed" in the kernel driver by:
> commit b791aba486285310aa9c2ced04df5ecd080a4548
> Author: Li Huang [putin.li@rock-chips.com](mailto:putin.li@rock-chips.com)
> Date: Thu Nov 14 09:17:13 2019 +0800
> 
> ```
> video/rockchip: rga2: Fixup wrong swap uv on YCrCb_420_P
> 
> Change-Id: I907c8687c5736fb489a21d16e87addf1f67e07c1
> Signed-off-by: Li Huang <putin.li@rock-chips.com>
> ```

resolved, thank you very much!
