### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by avafinger** [rockchip-linux/linux-rga#7]
I get this error message while building with meson, how can i fix this?

/usr/bin/python3 -V
Python 3.6.9

```
Native C++ compiler: ccache c++ (gcc 8.4.0 "c++ (Ubuntu/Linaro 8.4.0-1ubuntu1~18.04) 8.4.0")
Build machine cpu family: aarch64
Build machine cpu: aarch64
Found pkg-config: /usr/bin/pkg-config (0.29.1)
Determining dependency 'libdrm' with pkg-config executable '/usr/bin/pkg-config'
Native dependency libdrm found: YES 2.4.101
Message: Building with libdrm.

meson.build:57:10: ERROR: Item must be a list or one of <class 'str'>

```

**Comment by JeffyCN** [comment]
fixed in:
commit 87d95e87f11863b2027391ba38b422104cf52813
Author: Jeffy Chen <jeffy.chen@rock-chips.com>
Date:   Tue Aug 11 15:18:12 2020 +0800

    meson: Remove requires_private in pkgconfig

    We are not providing static version.

    Change-Id: Ia5b069688e16b7010d18202f5c928cf6947fa6bb
    Signed-off-by: Jeffy Chen <jeffy.chen@rock-chips.com>

the old meson 0.45.1 doesn't support using pkgconfig dependency in pkgconfig's requires fields.
