### ISSUE TITLE
failed to blit

### ISSUE THREAD

**Issue by avafinger** [rockchip-linux/linux-rga#8]
I have a blit fail, can you advise how to check if my build is working fine?

```
fd-vir-phy-hnd-format[18, (nil), (nil), 0, 0] 
rect[0, 0, 1920, 1080, 2816, 1080, 10, 0] 
f-blend-size-rotation-col-log-mmu[0, 0, 0, 0, 0, 0, 1] 
fd-vir-phy-hnd-format[-1, 0x7fa62e4010, (nil), 0, 0] 
rect[0, 0, 1920, 1080, 1920, -546, 10, 0] 
f-blend-size-rotation-col-log-mmu[0, 0, 0, 0, 0, 0, 1] 
This output the user patamaters when rga call blit fail 
Failed to do rga blit

```

**Comment by JeffyCN** [comment]
dup issue.

**Comment by fcorsino** [comment]
Same here, can someone indicate the dup issue?

**Comment by JeffyCN** [comment]
> Same here, can someone indicate the dup issue?

the original issue is about the usage of rga in ffmpeg rkmppdec:
https://github.com/JeffyCN/FFmpeg/issues/1

the dst buf hight is negative: -546
