### ISSUE TITLE
rga deb package doesn't have librga.so

### ISSUE THREAD

**Issue by amazingfate** [rockchip-linux/linux-rga#9]
I download the deb from https://github.com/rockchip-linux/rk-rootfs-build/blob/master/packages/armhf/rga/librga2_2.0.0-1_armhf.deb.
```
dpkg -L librga2
/.
/usr
/usr/lib
/usr/lib/arm-linux-gnueabihf
/usr/lib/arm-linux-gnueabihf/librga.so.2.0.0
/usr/share
/usr/share/doc
/usr/share/doc/librga2
/usr/share/doc/librga2/changelog.Debian.gz
/usr/share/doc/librga2/copyright
/usr/lib/arm-linux-gnueabihf/librga.so.2
```

**Comment by JeffyCN** [comment]
please note the lib*.so files are usually for develop, which should be in the "-dev" package(e.g. librga-dev_2.0.0-1_armhf.deb)
